openapi: 3.0.3
info:
  title: Todo API
  description: API for managing user todos with authentication and user isolation
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
              required:
                - email
                - password
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input
        '409':
          description: User already exists

  /api/auth/login:
    post:
      summary: Login user and return JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
        '401':
          description: Invalid credentials

  /api/users/{user_id}/todos:
    get:
      summary: Get all todos for a specific user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of todos for the user
          content:
            application/json:
              schema:
                type: object
                properties:
                  todos:
                    type: array
                    items:
                      $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user cannot access another user's todos
        '404':
          description: User not found

    post:
      summary: Create a new todo for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreate'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '400':
          description: Invalid input

  /api/users/{user_id}/todos/{todo_id}:
    get:
      summary: Get a specific todo for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Todo retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Todo not found

    put:
      summary: Update a specific todo for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdate'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Todo not found

    patch:
      summary: Toggle completion status of a specific todo
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
              required:
                - completed
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Todo not found

    delete:
      summary: Delete a specific todo for the user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: todo_id
          in: path
          required: true
          schema:
            type: string
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Todo deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Todo not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - created_at

    Todo:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
          default: false
        user_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed
        - user_id
        - created_at

    TodoCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        - title

    TodoUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean