apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentodo.fullname" . }}-backend
  labels:
    {{- include "agentodo.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "agentodo.backend.selectorLabels" . | nindent 4 }}
