apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentodo.fullname" . }}-frontend
  labels:
    {{- include "agentodo.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "agentodo.frontend.selectorLabels" . | nindent 4 }}
